### ISSUE TITLE
Process.close() error when using python 3.6.

### ISSUE THREAD

**Issue by JasperBoom** [genomescan/gsport#3]
Hello!

I was trying to run `gsport` to download data for one of our latest projects when I ran into this issues:
```
  File "/exports/sasc/jboom/miniconda3/envs/genomescan/bin/gsport", line 8, in <module>
    sys.exit(main())
  File "/exports/sasc/jboom/miniconda3/envs/genomescan/lib/python3.6/site-packages/gsport.py", line 455, in main
    download_all(session)
  File "/exports/sasc/jboom/miniconda3/envs/genomescan/lib/python3.6/site-packages/gsport.py", line 426, in download_all
    process.close()
AttributeError: 'Process' object has no attribute 'close'
```
I was able to solve this by upgrading my python version to 3.8.
Colleagues of mine have also been able to use `gsport` without this specific issue using python 3.9.

The [PyPI](https://pypi.org/project/gsport/) page suggests that `python>=3.6` is supported,
should that still be the case?

**Comment by SergeWielhouwer** [comment]
Thanks Jasper for describing this issue! The required Python version for gsport has been bumped up to version 3.7 in commit 362d1993dd897c1f8831adc38edfc7de0959eee2. This should resolve the missing attribute error for the Process object of the multiprocessing library. if this is not the case, please let us know by opening a new issue.

Source: https://docs.python.org/3/library/multiprocessing.html
![image](https://user-images.githubusercontent.com/87863674/213685219-5a476cee-c783-4f09-a2b4-c9e9c27cd3d5.png)
